### PR TITLE
Fix faceplanting aliens

### PR DESCRIPTION
**Pull request by syvvu**

### CODE REVIEW

**Review by hgrehm — APPROVED** [review]
Approving bc it runs as expected locally, but I will be real I don't understand the draw  func very well so might be best to wait for @zfxd to review as well

**Comment by syvvu** [comment]
@hgrehm Hannah I think there're some problems between commits fb4b1cf and b2af9d1, the graphics window isn't appearing for the second client

**Comment by hgrehm** [comment]
> > @hgrehm Hannah I think there're some problems between commits [fb4b1cf](https://github.com/ucsd-cse125-sp24/group4/commit/fb4b1cf50a61dc5fcaa7d0c11a260233cb270afb) and [b2af9d1](https://github.com/ucsd-cse125-sp24/group4/commit/b2af9d18cad1d2e15d763f9492e860d982dd2a22), the graphics window isn't appearing for the second client
> 
> ~Oh jeez sorry not sure how I missed all those commits in between... let me revert and redo~ Wait nvm I have no idea why that is... I'll look into it

O so in `client_core.cpp` I just hard-coded clients to vote that they're ready (still need to add user input). If you comment out
```
        send_vote(); // hard-coded to just vote READY immediately
```
in the `run` funcition, it'll wait until `NUM_CLIENTS` have connected, which is currently set to 2 in `server_core.h`.

**Review by zfxd — APPROVED** [review]
let's merge this :D

**Pull request merged**
